name: MLOps CI/CD Pipeline (LocalStack)

# 1. Triggers: Runs on PRs targeting 'main', and on direct pushes (merges) to 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-plan-apply:
    name: Terraform CI/CD Check & Deploy
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      AWS_DEFAULT_REGION: "us-east-1"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start LocalStack
        run: |
          docker run -d -p 4566:4566 -e DEFAULT_REGION=us-east-1 localstack/localstack:2.3.0
          sleep 15

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create Backend S3 Bucket
        run: aws --endpoint-url=http://localhost:4566 s3 mb s3://faizan-mlops-bucket-v2

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ./infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra

      # --- NEW STEP: THE CD (DEPLOYMENT) ---
      # This step will only execute when the code is pushed/merged to the main branch
      - name: Terraform Apply (Auto Deploy)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: ./infra
