name: MLOps CI/CD Pipeline (LocalStack)

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    name: Terraform Plan & Check
    runs-on: ubuntu-latest

    # Humne dummy keys yahan job ke start mein rakh di hain
    env:
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      AWS_DEFAULT_REGION: "us-east-1"

    steps:
      # Task A: Download the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Task B: Start LocalStack using raw Docker
      - name: Start LocalStack
        run: |
          docker run -d -p 4566:4566 -e DEFAULT_REGION=us-east-1 localstack/localstack:2.3.0
          sleep 15

      # Task C: Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # (Task D deleted! We don't need the official AWS action for LocalStack)

      # Task E: Initialize Terraform
      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ./infra

      # Task F: Run Terraform Plan to check infra changes
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra
